version: "3.7"

services:
  app:
    build: .
    image: amirpourmand/jupyter-docker-conda:latest
    ports:
      - 10000:8888
    volumes:
      - .:/home/user/app
    shm_size: 2gb
    restart: unless-stopped
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           device_ids: ["4"]
    #           capabilities: [gpu]

#https://stackoverflow.com/questions/58952478/changing-shared-memory-size-in-docker-compose